<Start> ::= { <Location> <GlobalDecl> }

<GlobalDecl> ::= <Function> | <Type> <Name> "=" <Const> | <Import>
<Import> ::= "import" <Javascript> "as" <Name> "(" <Params> ")"
<Function> ::= "function" <Name> "(" <Params> ")" "{" { <Statement> } "}"

<Statement> ::= <If> | <While> | <Single>
<Single> ::= <Declaration> | <Assignment> | <Discard> | <Return> | "break" | "continue"
<If> ::= "if" <Expr> "{" { <Statement> } "}" "else" "{" { <Statement> } "}"
<While> ::= "while" <Expr> "{" { <Statement> } "}"

<Declaration> ::= <Type> <Name> "=" <Expr>
<Assignment> ::= <Name> "=" <Expr>
<Discard> ::= <Expr>
<Return> ::= "return" <Expr>

<Expr> ::= <Call> | <Operation> | <List> | <Dictionary> | <Const>
<Operation> ::= <Expr> "+" <Expr> | <Expr> "*" <Expr> | <Expr> "/" <Expr> | <Expr> "-" <Expr>
              | <Expr> "^" <Expr> | <Expr> "++" <Expr> | <Expr> "and" <Expr> | <Expr> "or" <Expr>
              | <Expr> "==" <Expr> | <Expr> ">" <Expr> | <Expr> "<" <Expr> | <Expr> ">=" <Expr>
              | <Expr> "<=" <Expr> | <Expr> "!=" <Expr>
<Call> ::= <Name> "(" <Args> ")"
<List> ::= "[" {<Expr> ","} "]"
<Dictionary> ::= "{" {<Expr>:<Expr> ","} "}"

<Const> ::= <String> | <Number> | <Bool>
<Bool> ::= "True" | "False"
<String> ::= ### You know, a string ###
<Number> ::= ### Floating point stuff ###

<Args> ::= {<Expr> "," }
<Params> ::= {<Type> <Name> "," }
<Name> ::= ### Names! alphanumeric, dashes, underscores, etc ###
<Type> ::= "String" | "Num" | "List" | "Struct" | "Void"
